### PR TITLE
fix: config.reporter undefined bug

### PR DESCRIPTION
**Pull request by yinhangfeng**
fix: #374

### CODE REVIEW

**Comment by thymikee** [comment]
Thanks! Mind taking a look at Flow error?

**Comment by thymikee** [comment]
@yinhangfeng I've updated your PR, can you check if it works for you?

**Comment by yinhangfeng** [comment]
> @yinhangfeng I've updated your PR, can you check if it works for you?

it works, thank you

**Comment by thymikee** [comment]
cc @fson

**Comment by grabbou** [comment]
Looks good! I wouldn't touch `getDefaultConfig` function tho, I would just keep the logic where it was before this PR.

**Comment by grabbou** [comment]
@yinhangfeng once again, thank you for sending this PR! Please let me know if you are going to have some time anytime soon to address the feedback. We would like to ship this PR soon and make a new release of the CLI!

If not, it's all right :) We will rebase and continue work on top of your PR.

**Comment by thymikee** [comment]
@grabbou can you share some insights on why you think modifying the `getDefaultConfig` fn is bad here? To me it corresponds nicely, because `reporter` is a part of Metro config and in certain cases it is a default for us, with or without it. It feels even more clunky adding `reporter` conditionally to the already constructed default config.

**Comment by grabbou** [comment]
I don’t like coupling default configuration with CLI options which are
meant to override the default, inferred (from context object) configuration
that this function returns.

There used to be a separate function for overriding config with CLI options
which we got rid of as Metro implemented this internally.

Passing the whole options to the function is in my opinion confusing,
because we do not explicitly handle all other CLI options, except for
reporter. We leave the rest up to Metro.

**Comment by grabbou** [comment]
@thymikee please review after changes.

**Pull request merged**
