### PR TITLE
fix: correctly list ios devices and simulators

### LINKED ISSUE #1845: iOS: `react-native bundle` fails to find target simulator
## Environment

```
System:
    OS: macOS 12.6.3
    CPU: (10) arm64 Apple M1 Max
    Memory: 4.24 GB / 64.00 GB
    Shell: 5.8.1 - /bin/zsh
  Binaries:
    Node: 18.14.1 - /private/var/folders/j0/5zfnwvyd4sb15smylklx03m00000gn/T/xfs-985c11d4/node
    Yarn: 3.4.1 - /private/var/folders/j0/5zfnwvyd4sb15smylklx03m00000gn/T/xfs-985c11d4/yarn
    npm: 9.3.1 - ~/.local/bin/npm
    Watchman: 2023.01.30.00 - /opt/homebrew/bin/watchman
  Managers:
    CocoaPods: 1.11.3 - ~/.gem/bin/pod
  SDKs:
    iOS SDK:
      Platforms: DriverKit 22.2, iOS 16.2, macOS 13.1, tvOS 16.1, watchOS 9.1
    Android SDK:
      API Levels: 31, 33
      Build Tools: 30.0.3, 31.0.0, 33.0.0
      System Images: android-33 | Google APIs ARM 64 v8a
      Android NDK: Not Found
  IDEs:
    Android Studio: 2021.2 AI-212.5712.43.2112.8815526
    Xcode: 14.2/14C18 - /usr/bin/xcodebuild
  Languages:
    Java: 11.0.18 - /usr/bin/javac
  npmPackages:
    @react-native-community/cli: 10.1.3 => 10.1.3
    react: 18.2.0 => 18.2.0
    react-native: 0.71.3 => 0.71.3
    react-native-macos: Not Found
  npmGlobalPackages:
    *react-native*: Not Found
```

## Description

`react-native run-ios` fails to find target simulator, even with `--simulator 'iPhone 14'`. It's using a specifier that isn't listed under available destinations:

```
2023-02-22 11:27:45.294 xcodebuild[12075:16449994] Writing error result bundle to /var/folders/j0/5zfnwvyd4sb15smylklx03m00000gn/T/ResultBundle_2023-22-02_11-27-0045.xcresult
xcodebuild: error: Unable to find a destination matching the provided destination specifier:
		{ id:00000000-0000-0000-0000-69C2E79AE15B }

	The requested device could not be found because no available devices matched the request.

	Available destinations for the "Example" scheme:
		{ platform:macOS, arch:arm64, variant:Designed for [iPad,iPhone], id:00000000-0000000000000000 }
		{ platform:iOS, id:dvtdevice-DVTiPhonePlaceholder-iphoneos:placeholder, name:Any iOS Device }
		{ platform:iOS Simulator, id:dvtdevice-DVTiOSDeviceSimulatorPlaceholder-iphonesimulator:placeholder, name:Any iOS Simulator Device }
		{ platform:iOS Simulator, id:00000000-0000-0000-0000-39E84C80FC4F, OS:16.2, name:iPad (10th generation) }
		{ platform:iOS Simulator, id:00000000-0000-0000-0000-A9BD2F2E6901, OS:16.2, name:iPad Air (5th generation) }
		{ platform:iOS Simulator, id:00000000-0000-0000-0000-D4C952251A5D, OS:16.2, name:iPad Pro (11-inch) (4th generation) }
		{ platform:iOS Simulator, id:00000000-0000-0000-0000-C02EF1196518, OS:16.2, name:iPad Pro (12.9-inch) (6th generation) }
		{ platform:iOS Simulator, id:00000000-0000-0000-0000-A58EBFA64F1C, OS:16.2, name:iPad mini (6th generation) }
		{ platform:iOS Simulator, id:00000000-0000-0000-0000-A2264D6D15EB, OS:16.2, name:iPhone 14 }
		{ platform:iOS Simulator, id:00000000-0000-0000-0000-A711FB324DD4, OS:16.2, name:iPhone 14 Plus }
		{ platform:iOS Simulator, id:00000000-0000-0000-0000-15EBD10C046C, OS:16.2, name:iPhone 14 Pro }
		{ platform:iOS Simulator, id:00000000-0000-0000-0000-D4338FF8FC9B, OS:16.2, name:iPhone 14 Pro Max }
		{ platform:iOS Simulator, id:00000000-0000-0000-0000-9F11116E74DA, OS:16.2, name:iPhone SE (3rd generation) }
```

## Reproducible Demo

```
git clone https://github.com/microsoft/react-native-test-app.git
cd react-native-test-app
npm run set-react-version 0.71
yarn
cd example
pod install --project-directory=ios
yarn ios
```

### PR DESCRIPTION
**Pull request by roryf**
Summary:
---------

Backports #1823 to 10.x branch.

After updating to RN 0.71.3 I was experiencing issue similar to #1807 (it would try to use my laptop as target device), hoping this can be merged to a 10.x release and fixed in a new RN 0.71.x version.

Fixes #1845

Test Plan:
----------

- Ran `node ../cli/packages/cli/build/bin.js run-ios`  verified it launched app in expected iPhone 14 simulator, where before it would error with https://github.com/facebook/react-native/issues/35917#issuecomment-1460894084
- Ran `node ../cli/packages/cli/build/bin.js run-ios --list-devices` verified it listed all available simulators, and not my laptop as previous
```
> node ../cli/packages/cli/build/bin.js run-ios --list-devices            
warn Multiple Podfiles were found: ios/Podfile,vendor/bundle/ruby/2.7.0/gems/cocoapods-core-1.11.3/lib/cocoapods-core/Podfile. Choosing ios/Podfile automatically. If you would like to select a different one, you can configure it via "project.ios.sourceDir". You can learn more about it here: https://github.com/react-native-community/cli/blob/master/docs/configuration.md
info Found Xcode workspace "Foo.xcworkspace"
? Select the device you want to use › - Use arrow-keys. Return to submit.
❯   iPhone 12 mini 
    iPhone 8 Plus 
    iPad (10th generation) 
    iPhone 11 
    iPhone 13 
    iPhone SE (3rd generation) 
    iPod touch (7th generation) 
    iPhone 14 
    iPhone 14 Pro 
  ↓ iPhone 12 Pro
```

### CODE REVIEW

**Comment by adamTrz** [comment]
Thanks for the PR @roryf 🎉 

Could you please resolve failing test? And then we can merge :)

**Comment by roryf** [comment]
@adamTrz should be resolved now

**Comment by roryf** [comment]
@adamTrz @thymikee thanks for merging, can a new 10.x release be cut?

**Comment by thymikee** [comment]
hey @roryf, I've released these packages:
```
 - @react-native-community/cli-doctor@10.2.1
 - @react-native-community/cli-platform-ios@10.2.1
 - @react-native-community/cli@10.2.1
 ```
 They won't be automatically pulled by the RN 0.71, so we'd need to send a request to update the CLI

**Comment by lucasbento** [comment]
@thymikee @szymonrybczak @roryf could we potentially make this the default behaviour in case it fails to run `run-ios` on the first picked device? Basically prompt the user for selecting the device if it failed the first time.

Asking as the command seems to be defaulting to my Apple Watch (something to look into as well, I would be happy to do it) and might default to my physical device which will potentially fail as well as it's sometimes not in the same network.

**Comment by thrandale** [comment]
I am also seeing where it is picking my apple watch instead of my phone. And failing because of it
image
image

**Pull request merged**
