### PR TITLE
chore: update @react-native-community/eslint-config to v2

### PR DESCRIPTION
**Pull request by imoans**
Summary:
---------

- Update @react-native-community/eslint-config to the latest version(1.1.0).
- Fixed errors of prettier/prettier rule by --fix option.
- Change docker image of circle ci from circleci/node:8 to circleci/node:10
    - Becase node v8 has not been supported from 2019/12/31

Test Plan:
----------

 I ran every test mentioned in [CONTRIBUTING.md](https://github.com/react-native-community/cli/blob/master/CONTRIBUTING.md#testing-init-command).

### CODE REVIEW

**Comment by thymikee** [comment]
We can only merge it once we start landing breaking changes for v5

**Comment by grabbou** [comment]
I think it would be a good moment to start refactoring that branch finally

**Comment by thymikee** [comment]
A rebase and re-running `eslint --fix` should be enough

**Review by thymikee — APPROVED** [review]
LGTM 👍

**Pull request merged**
