### PR TITLE
chore: bump metro to match supported RN versions

### PR DESCRIPTION
**Pull request by Simek**
Summary:
---------

This PR bumps Metro used in the `cli` package to version `0.62.0`. I have selected this version to match [minimal supported React Native](https://github.com/react-native-community/cli/blob/master/packages/cli/package.json#L68) version by V4 cli.

This bump also fixes most of metro related warnings occurring during `init`:
Screenshot 2020-09-28 at 23 01 53

Test Plan:
----------

Test run (`yarn test`) was successful.

### CODE REVIEW

**Comment by Simek** [comment]
CI fail seems to be unrelated to the changes (it looks like network related problem or too short timeout):
* https://dev.azure.com/react-native-community/cli/_build/results?buildId=1501&view=logs&j=12f1170f-54f2-53f3-20dd-22fc7dff55f9&t=bd05475d-acb5-5619-3ccb-c46842dbc997&l=62

Screenshot 2020-09-28 at 23 23 20

**Comment by thymikee** [comment]
Thanks! I think this is the last missing piece to get cli@5 out. 

RN 0.64 is not yet cut, and on master there's metro@0.63 already: 
- https://github.com/facebook/react-native/blob/master/template/package.json#L23
- https://github.com/facebook/react-native/blob/29f5dc2ae0091e3b230687a1870512316c156e87/package.json#L100-L103

So let's go with metro@0.63 :)

**Review by thymikee — APPROVED** [review]

**Comment by Simek** [comment]
Should I bump the Metro to `0.62` in the `4.x` branch to maintain the initial goal of resolving the warnings for the current major version?

**Comment by thymikee** [comment]
Bumping Metro version is potentially breaking, so I'd like to avoid that in a minor release.

**Comment by grabbou** [comment]
Thank you. Merging and preparing master for the cut.

**Comment by grabbou** [comment]
On that note, do we need to hardcode Metro version here? How about we make it flexible and always use latest in the `devDependencies`?

**Pull request merged**
