### PR TITLE
Bumping metro packages to v0.57.0, which fixes a Windows CLI bug

### LINKED ISSUE #853: Please bump metro version to 0.57.0 to solve issues on Windows with Node v12.x.x
Bug is described and fixed with https://github.com/facebook/metro/commit/7c6f30b592b2fb23cee55b54f1aa4b7a522dec18. Commit was accepted and released under metro v0.57.0.

### LINKED ISSUE #900: Warnings when starting metro on 0.62 branch
## Environment

<details>
<pre>
System:
    OS: macOS 10.14.6
    CPU: (12) x64 Intel(R) Core(TM) i9-8950HK CPU @ 2.90GHz
    Memory: 10.47 GB / 32.00 GB
    Shell: 5.3 - /bin/zsh
  Binaries:
    Node: 12.9.1 - /usr/local/bin/node
    Yarn: 1.17.3 - /usr/local/bin/yarn
    npm: 6.12.0 - /usr/local/bin/npm
    Watchman: 20191102.030014 - /opt/facebook/bin/watchman
  SDKs:
    iOS SDK:
      Platforms: iOS 13.2, DriverKit 19.0, macOS 10.15, tvOS 13.2, watchOS 6.1
    Android SDK:
      API Levels: 23, 24, 25, 26, 27, 28, 29
      Build Tools: 23.0.1, 25.0.0, 25.0.2, 28.0.3, 29.0.2
      System Images: android-24 | Intel x86 Atom, android-24 | Google APIs Intel x86 Atom_64
  IDEs:
    Android Studio: 3.5 AI-191.8026.42.35.5791312
    Xcode: 11.2.1/11B500 - /usr/bin/xcodebuild
  npmPackages:
    @react-native-community/cli: ^3.0.0 => 3.0.1 
    react: 16.11.0 => 16.11.0 
  npmGlobalPackages:
    react-native-cli: 2.0.1
</pre>
</details>

## Description

Running `./scripts/packager.sh` prints two different warnings for unknown configs.

## Reproducible Demo

- Clone react-native
- Checkout 0.62-stable branch
- `./scripts/packager.sh

Screen Shot 2019-12-19 at 9 29 49 AM

### PR DESCRIPTION
**Pull request by tad3j**
Windows CLI bug solved with https://github.com/facebook/metro/commit/7c6f30b592b2fb23cee55b54f1aa4b7a522dec18 and released under v0.57.0.

Summary:
---------

Updating all metro related packages to v0.57.0

Fixes #900
Fixes #853

Test Plan:
----------

I ran test command bug seems like there are some issues:
Test Suites: 1 failed, 71 passed, 72 total
Tests:       5 failed, 2 skipped, 2 todo, 263 passed, 272 total
Snapshots:   6 failed, 20 passed, 26 total

Not sure if it's due to new metro version...

### CODE REVIEW

**Comment by grabbou** [comment]
Thanks for sending the PR over. Don't worry with the `windows` CI, it's been failing for some reason. I have to debug this myself when I get time after my windows.

CC: @TheSavior who would be the right person (or maybe that's you - in that case, awesome) to make sure this is safe to perform and distribute to 0.61?

**Comment by TheSavior** [comment]
I’m not sure. What is normally involved when bumping metro? What can go wrong?

**Comment by grabbou** [comment]
Historically, we've been cautious while doing so. There was this approach of not changing Metro versions when doing `patch` releases of React Native - only bumping for major. 

If this is no longer the case and we can safely ship Metro as any other dependency, then I guess we should just do it.

**Comment by thymikee** [comment]
Had to remove usage of `createBlacklist`, because Metro got rid of it in 0.57.
For now I tested running and building on Android and it seems to work fine. Will try iOS soon

**Comment by SaeedZhiany** [comment]
@thymikee 

Can you please merge and publish this PR? I'm working on a react and a react-native project at the same time and for some reason, I can't downgrade my node version.

Thanks

**Comment by thymikee** [comment]
FYI: https://github.com/facebook/metro/releases/tag/v0.56.4. This PR is no longer necessary for 3.x, but I'll happily port it to 4.x soonish.

**Comment by grabbou** [comment]
Just a heads up. I am going to rebase `next` branch and we will merge this.

**Comment by thymikee** [comment]
@grabbou I think we could put Metro 0.57 in the v3.x, it worked well in my testing, but of course more is welcome.

Also, RN 0.62 uses Metro 0.57 or 0.58 so we need to account for that.

**Comment by grabbou** [comment]
Okay, we will need to bump to 0.58 for 0.62, so I guess we can experiment with bumping to 0.58 as well. 

I would like to define a policy / steps involved in bumping Metro releases so that we can do it with more confidence. In theory, it shouldn't introduce new regressions if they follow semver.

**Pull request merged**
