### PR TITLE
Fix package name for main activity when appId set

### PR DESCRIPTION
**Pull request by grahamsmith**
Summary:
---------

Working on a white label feature for an app, I ran into an issue where I needed to set the appId differently to the package name and an explicit main activity in a different package.

For example my build.gradle application ID could be `com.test` and the manifest package be `com.test` however my main activity, from a dependency, has been set explicitly set in the manifest as `com.dependency.AnActivity`.

When running:

`react-native run-android --appId com.test --main-activity com.dependency.AnActivity`

the result would be:

`Error: Activity class {com.test/com.packagename.com.dependency.AnActivity} does not exist.`

I have made a small change to allow an explicit main activity with package name set.

Test Plan:
----------

Run similar to `react-native run-android --appId com.test --main-activity com.dependency.AnActivity` and expect the explicit activity to start.

Run `react-native run-android --appId com.test --main-activity AnActivity` and expect the detected package name to be the prefix of the specified activity.

### CODE REVIEW

**Comment by thymikee** [comment]
Lint is failing, can you run `yarn lint --fix`?

**Comment by grahamsmith** [comment]
@thymikee - is there anything I need to do to get this merged? First time contributor to this repo so just checking.

**Comment by thymikee** [comment]
I'd like @Esemesek and @troZee to have a look as well :)

**Comment by grahamsmith** [comment]
Sorry to be that guy but can I get an ETA to merge this please? It's blocking some other OSS updates going out that will fix some issues for others.

**Comment by thymikee** [comment]
@grabbou please make sure to prioritize this on your ramp up today, it would be lovely to have it in and released today/tomorrow :)

**Comment by thymikee** [comment]
@grahamsmith sorry for our slow response here, we were occupied with lots of extra activities recently, including organizing and preparing for React Native EU (which starts in few minutes!! stream here: https://www.youtube.com/watch?v=DduUntL2Sv4). Hopefully we'll regain some time to get back to CLI maintenance :). I also hope we didn't discouraged you from future contributions 😊

**Comment by thymikee** [comment]
@grahamsmith this is now released in v4.13, thank you!

**Comment by grahamsmith** [comment]
Amazing news. Thanks for sorting that out.

**Pull request merged**
