### PR TITLE
Follow symlinks until a non-symlink is found

### PR DESCRIPTION
**Pull request by aleclarson**
Summary:
---------

In `node_modules`, follow symlinks until the "real path" is found.

Migrated from here: https://github.com/facebook/react-native/commit/fa6191f6ac65a8a303a22933e183e1f5a7381976

Test Plan:
----------

None yet.

### CODE REVIEW

**Comment by grabbou** [comment]
Mind fixing tests and adding one test case to cover this scenario?

**Comment by aleclarson** [comment]
When I can find time, but it'll be a while.

**Comment by thymikee** [comment]
@aleclarson this looks good but I'd like to add more an extra test. Added a check for `visited` array size, which fixes both unit tests and my test setup.

Btw while testing this I've finally found a way for us to run linked `start` command:

```sh
# when @react-native-community/cli is linked
REACT_NATIVE_APP_ROOT=/path/to/react-native-cli yarn react-native start
# or when it's not
REACT_NATIVE_APP_ROOT=/path/to/react-native-cli/packages/cli/build start
```
cc @grabbou @pbitkowski

**Comment by grabbou** [comment]
I am going to close this due to inactivity. Feel free to re-open or submit once again with addressed changes.

**Comment by rajatgyl** [comment]
I am getting this error while running with react-native run-android command however I was able to run this with the command react-native run-android --deviceId {DEVICE ID IN ADB DEVICES}.
issue but can not run this with react-native run-android command.
{
react-native-cli: 2.0.1
react-native: 0.54.2
}

**Comment by thymikee** [comment]
You have ancient RN version. This cli ships with 0.59. Please upgrade if you can

**Pull request closed without merging**
