### PR TITLE
chore: Changing node version missed during metro dependencies upgrade

### PR DESCRIPTION
**Pull request by arushikesarwani94**
Summary:
---------

Updating the node version missed in https://github.com/react-native-community/cli/pull/2007/ as 18 is the Current version, will be LTS in October.

Test Plan:
----------

Tests pass

### CODE REVIEW

**Review by thymikee — APPROVED** [review]
Thanks!

**Comment by thymikee** [comment]
Install fails on node 20. I actually had the same locally and went back to 18 as I didn't have time to investigate

**Comment by szymonrybczak** [comment]
I think this is problem related to `node-gyp`, as we're on old version -`node-gyp` is one of dependencies that comes with `lerna`. I bumped `leran` locally from `4.0.0` to `5.0.0` and the project is building for me correctly.

**Comment by szymonrybczak** [comment]
@arushikesarwani94 mind rebasing on top of main?

**Comment by arushikesarwani94** [comment]
> Hm, looks like CI is failing on creating project on node 20 on Ubuntu, interesting. 🤔

Not sure why this would just fail on Ubuntu for Node 20. 

cc: @thymikee Any idea what could be going on ?

**Pull request merged**
