### PR TITLE
fix: correctly list ios devices and simulators

### LINKED ISSUE #1807: iOS CLI Run Fails with Incorrect Device ID in 10.1.x
## Environment
```
$ yarn react-native info
info Fetching system and libraries information...
System:
    OS: macOS 13.1
    CPU: (10) arm64 Apple M1 Max
    Memory: 1.39 GB / 64.00 GB
    Shell: 5.2.15 - /opt/homebrew/bin/bash
  Binaries:
    Node: 19.4.0 - /private/var/folders/fq/d3nyh22d32j20vxw03_hl5gh0000gn/T/xfs-b0210ea0/node
    Yarn: 3.2.2 - /private/var/folders/fq/d3nyh22d32j20vxw03_hl5gh0000gn/T/xfs-b0210ea0/yarn
    npm: 9.3.0 - /opt/homebrew/bin/npm
    Watchman: 2023.01.09.00 - /opt/homebrew/bin/watchman
  Managers:
    CocoaPods: 1.11.3 - /Users/brian/.rbenv/shims/pod
  SDKs:
    iOS SDK:
      Platforms: DriverKit 22.2, iOS 16.2, macOS 13.1, tvOS 16.1, watchOS 9.1
    Android SDK:
      API Levels: 29, 30, 31, 33
      Build Tools: 26.0.2, 26.0.3, 28.0.3, 29.0.2, 30.0.2, 30.0.3, 31.0.0, 31.0.0, 31.0.0, 33.0.0
      System Images: android-31 | Google Play ARM 64 v8a
      Android NDK: Not Found
  IDEs:
    Android Studio: 2022.1 AI-221.6008.13.2211.9477386
    Xcode: 14.2/14C18 - /usr/bin/xcodebuild
  Languages:
    Java: 11.0.11 - /usr/bin/javac
  npmPackages:
    @react-native-community/cli: Not Found
    react: 18.2.0 => 18.2.0 
    react-native: 0.71.1 => 0.71.1 
    react-native-macos: Not Found
  npmGlobalPackages:
    *react-native*: Not Found
```

## Description
`react-native run-ios` (in `cli-platform-ios`) seems to fail with versions `10.1.x`. I've tested with `@react-native-community/cli-platform-ios` versions `10.1.0` and `10.1.1`. The command only works when fixing the resolution to `10.0.0`.

We have custom scripts to run different configs + schemes. Here's an example of one that is failing:

```
"ios:staging": "react-native run-ios --configuration Debug-staging --scheme staging",
```

On `10.1.x`, it fails with:

```
$ yarn ios:staging
info Found Xcode workspace "TTW3.xcworkspace"
info Found booted Living Room Apple TV, iPhone 14
info Building (using "xcodebuild -workspace TTW3.xcworkspace -configuration Debug-staging -scheme staging -destination id=3542d5b87c1a194be3554b3e9743676d9937011c")
error Failed to build iOS project. We ran "xcodebuild" command but it exited with error code 70. To debug build logs further, consider building your app with Xcode.app, by opening TTW3.xcworkspace.
```

When running against `10.0.0`, the output is different:

```
$ yarn ios:staging
info Found Xcode workspace "TTW3.xcworkspace"
info Building (using "xcodebuild -workspace TTW3.xcworkspace -configuration Debug-staging -scheme staging -destination id=874EC276-8C56-413E-888B-1CA8D783E64D")
```

And from there, it builds and runs successfully.

I suspect the issue has to do with identifying the device/simulator to run on? See the `-destination` difference in the output between the two. The `id` that is found in `10.1.x` doesn't correspond to any device ID.

It's worth noting that running from Xcode works without issue in all cases, so this is clearly a CLI issue.

## Reproducible Demo
I'm not sure the best way to share a reproducible test case right now. Hopefully the above is information sufficient to investigate, but if you need more details, let me know 🙏

### LINKED ISSUE #1816: How does `react-native run-ios` determine the arguments when invoking `xcodebuild`?
I'm running into an issue trying to run my React Native app after updating to 0.71.2. 

When using `react-native run-ios`, I see that a `xcodebuild` command is ran:
```
xcodebuild -workspace app.xcworkspace -configuration Debug -scheme app -destination id=714D33E1-C723-5040-A13C-7CE0C3FD5A5B"
```

This has worked fine for months however since this update it seems this destination UDID no longer exists. Resulting in xcodebuild failing:
```
error Failed to build iOS project. We ran "xcodebuild" command but it exited with error code 70. To debug build logs further, consider building your app with Xcode.app, by opening app.xcworkspace.
```

Building the app using Xcode works without problems, and it opens on the simulator I selected in Xcode.

My question is: where is this destination UDID coming from? I'm not passing anything, I've cleaned my build folders, I've updated Xcode to latest (14.2), I've cleared the DerivedData and simulators, I've manually changed the selected simulator in Xcode, yet this problem still persists.

Manually overriding the UDID using the `--udid` flag like so:
```
npx react-native run-ios --udid="ADC901D0-E79F-4632-88E3-20B274A09E35"
```
DOES work, however, this does not "update" the stored UDID, and when I try to go back to just `npx react-native run-ios`, it still invokes xcodebuild with the wrong/old UDID.

How can I reset this? How can I change the destination permanently without passing the --udid flag?
Any help would be greatly appreciated.

### PR DESCRIPTION
**Pull request by adamTrz**
Summary:
---------

Switched from `xcrun xctrace list devices` to `xcrun xcdevice list` when gathering info about available iOS devices and simulators. 
Previous one wasn't providing enough information to distinguish between AppleTV / macOS / iPhone devices leading to unexpected behaviours. 

Fixes #1816 
Fixes #1807 
Closes #1786 

Test Plan:
----------
Connect as many Apple devices as possible and:
-  try to run `run-ios` - it should try to launch RN App on all valid devices and simulators
- try to run `run-ios --list-devices` - it should list all valid devices (even not available ones) and simulators

image

### CODE REVIEW

**Review by szymonrybczak — APPROVED** [review]
Perfect work @adamTrz! 🙌

**Comment by thymikee** [comment]
Can you check if `xcrun xcdevice` is available on last 2 or 3 versions of Xcode?

**Comment by adamTrz** [comment]
> Can you check if `xcrun xcdevice` is available on last 2 or 3 versions of Xcode?

It's working on xCode 12 and 13, couldn't get my hands on lower versions yet ...

**Comment by thymikee** [comment]
Awesome! That's more than enough I think :D

**Pull request merged**
