### PR TITLE
fix: Fix watchMode process logs not showing color

### PR DESCRIPTION
**Pull request by SubsequentlySneeds**
Summary:
---------

When selecting "run on Android" from the Metro menu, the first info label is bolded and cyan, but the second one prints without color or bolding:

Code_ojM1HKCg96
(VSCode terminal)

This is because the child process spawns without color by default, even if the parent has color enabled. This causes chalk to print without color escape sequences to the child stdout, which is then piped back to the parent stdout without color, even though it is capable of displaying it.

This change simply adds an env variable to force color in the child process if the parent supports color.

Test Plan:
----------

Pasted the code into the transpiled watchMode.js file (replacing "chalk" with "_chalk().default" for ES Module interop) in the React Native project the issue was first observed in and re-ran the same operation:

Code_hGwZ4IvBmN

Checklist
----------

- [x] Documentation is up to date to reflect these changes.
- [x] Follows commit message convention described in [CONTRIBUTING.md](https://github.com/react-native-community/cli/blob/main/CONTRIBUTING.md#commit-message-convention)

### CODE REVIEW

**Review by thymikee — APPROVED** [review]
Nice find, thank you!

**Comment by thymikee** [comment]
We've made some changes to the watchMode, @SubsequentlySneeds would you mind rebasing? 🙏🏼

**Comment by SubsequentlySneeds** [comment]
Rebased to the latest watchMode.ts

**Review by adamTrz — APPROVED** [review]

**Comment by thymikee** [comment]
cc @huntie – as we're freezing `cli-plugin-metro`, could you import this change to [community-cli-plugin](https://github.com/facebook/react-native/tree/main/packages/community-cli-plugin)?

@szymonrybczak would like to test it on Windows as well

**Comment by szymonrybczak** [comment]
Closing this PR, as the code is not longer in this repository - we migrated that part of codebase to React Native repo, and as I can see @huntie [already added](https://github.com/facebook/react-native/pull/39074) this change. Thanks for contribution!

**Pull request closed without merging**
