### PR TITLE
feat(doctor): adjust healthchecks based on where command was ran

### PR DESCRIPTION
**Pull request by szymonrybczak**
Summary:
---------

Update `doctor` command to detect if command was ran in React Native app, if yes we can show the project specific checks. 

Test plan
----------
1. Clone the repository and do all the required steps from the [Contributing guide](https://github.com/react-native-community/cli/blob/main/CONTRIBUTING.md)
2. Run this command outside of React Native project, and you should see only checks related to setup.

```sh
node /path/to/react-native-cli/packages/cli/build/bin.js doctor
```
```
Common
 ✓ Node.js - Required to execute JavaScript code
 ✓ yarn - Required to install NPM dependencies
 ✓ Watchman - Used for watching changes in the filesystem when in development mode

Android
 ✓ Adb - Required to verify if the android device is attached correctly
 ✓ JDK - Required to compile Java code
 ✓ Android Studio - Required for building and installing your app on Android
 ✓ ANDROID_HOME - Environment variable that points to your Android SDK installation

iOS
 ✓ Xcode - Required for building and installing your app on iOS
 ✓ Ruby
 ✓ CocoaPods - Required for installing iOS dependencies
 ✓ ios-deploy - Required for installing your app on a physical device with the CLI

Errors:   0
Warnings: 0
```
3. Run this command inside of React Native project, and you should see checks related to setup and to project.
```sh
node /path/to/react-native-cli/packages/cli/build/bin.js doctor
```
```
Common
 ✓ Node.js - Required to execute JavaScript code
 ✓ yarn - Required to install NPM dependencies
 ✓ Watchman - Used for watching changes in the filesystem when in development mode
 ✓ Metro - Required for bundling the JavaScript code

Android
 ✓ Adb - Required to verify if the android device is attached correctly
 ✓ JDK - Required to compile Java code
 ✓ Android Studio - Required for building and installing your app on Android
 ✓ ANDROID_HOME - Environment variable that points to your Android SDK installation
 ✓ Android SDK - Required for building and installing your app on Android

iOS
 ✓ Xcode - Required for building and installing your app on iOS
 ✓ Ruby - Required for installing iOS dependencies
 ✓ CocoaPods - Required for installing iOS dependencies
 ✓ ios-deploy - Required for installing your app on a physical device with the CLI
 ✓ .xcode.env - File to customize Xcode environment

Errors:   0
Warnings: 0
```

Checklist
----------

- [x] Documentation is up to date to reflect these changes.
- [x] Follows commit message convention described in [CONTRIBUTING.md](https://github.com/react-native-community/cli/blob/main/CONTRIBUTING.md#commit-message-convention)

### CODE REVIEW

**Comment by thymikee** [comment]
Initially we thought about using doctor as a tool to verify that the environment is set up correctly to init an app. I guess that use case could be moved to init anyway

**Comment by thymikee** [comment]
cc @arushikesarwani94 wdyt?

**Comment by arushikesarwani94** [comment]
ATM doctor is definitely a tool to verify that the environment is set up correctly to init an app. Not yet moved completely to init. This is also majorly used in issues reported in RN repo as a recommendation to run doctor and paste it's output to quickly spot something wrong with the set-up. The plan was also to move RN packages like `cli-doctor` out of CLI to RN repo but nothing concrete has happened on that front.
cc : @cortinico

**Comment by szymonrybczak** [comment]
What is also important to take into account that right now we have few parts of `doctor` that depends strongly on a project. To name few: `.xcode.env` and starting Metro. I think we should somehow maybe check if we're outside of project, if yes do show project-specific options.

**Comment by cortinico** [comment]
> I think we should somehow maybe check if we're outside of project, if yes do not show project-specific options.

IMHO This should be the preferred approach.

> that it doesn't make sense to allow running this command outside of project.

My 2c: It still makes sense to run outside of a project.
For example, say that you want to check if your machine is correctly configured to run a React Native project. Some checks are project specific, but others are not (i.e. you will need an Android/iOS SDK at some point).

**Comment by szymonrybczak** [comment]
@cortinico make sense, so I will adjust this PR to check if the command was ran outside React Native project if yes I will hide the project specific checks. 👍

**Review by adamTrz — APPROVED** [review]

**Review by thymikee — APPROVED** [review]

**Comment by szymonrybczak** [comment]
After final testing, the `loadConfig` function also returns config when running command e.g. inside CLI - when calling `config.reactNativePath`, we can be sure that we're in React Native project.

**Pull request merged**
