### PR TITLE
fix(cli): bump metro to 0.66.1

### PR DESCRIPTION
**Pull request by tido64**
Summary:
---------

Latest `metro` fixes [issues](https://github.com/facebook/metro/releases/tag/v0.66.1) that will be beneficial to include in 0.65.

Test Plan:
----------

Since this change only touches dependencies, existing tests should pass.

### CODE REVIEW

**Comment by tido64** [comment]
cc @afoxman @kelset @NickGerleman

**Review by thymikee — APPROVED** [review]
Thanks!

**Comment by thymikee** [comment]
Btw, can we also upgrade `metro-memory-fs` in root package.json?

**Comment by tido64** [comment]
The reported build failures don't seem to be related to these changes. Is that something you plan to fix separately? Can we get this merged?

**Pull request merged**
