### PR TITLE
feat: Allow passing in MainPackageConfig to PackageList

### PR DESCRIPTION
**Pull request by akshetpandey**
Summary:
---------

This allow customizing configuration for the MainReactPackage.
Right now this is limited to changing how FrescoModule gets initialized
but in the future this can allow changes in behavior for other core modules

Test Plan:
----------

Since this is a template only change, it shouldn't require any tests.
I have verified that this is not a breaking change for existing users.

### CODE REVIEW

**Comment by akshetpandey** [comment]
One use case for this is here: [MainApplication.java](https://github.com/akshetpandey/react-native-cronet/blob/master/example/android/app/src/main/java/com/example/MainApplication.java#L29)

**Comment by thymikee** [comment]
I'm good with this, but would also like @Salakar and @dulmandakh to take a look. In the meantime, can you please update the documentation?

**Comment by akshetpandey** [comment]
I am not sure if PackageList is documented directly.

The closest thing I could find was here [autolinking.md#platform-android](https://github.com/react-native-community/cli/blob/8c2d5b5f337db02c8868c627d9e4a3b39e0af329/docs/autolinking.md#platform-android)

I can change the example here: [helloworld/MainApplication.java](https://github.com/facebook/react-native/blob/769e35ba5f4c31ef913035a5cc8bc0e88546ca55/template/android/app/src/main/java/com/helloworld/MainApplication.java#L22-L28) but that is in the react-native repo

**Comment by thymikee** [comment]
There's https://github.com/react-native-community/cli/blob/8c2d5b5f337db02c8868c627d9e4a3b39e0af329/docs/dependencies.md#platformsandroidpackageinstance. We need to restructure the docs so that they're more accessible, but not sure about the approach yet

**Comment by akshetpandey** [comment]
@thymikee : I am not sure what I should do with that documentation. We probably need to to figure out the right API we want to expose for users to manually configure their modules.

One option is, to ask users to subclass MainPackageConfig and pass in an instance of that when they create PackageList in MainApplication, or whenever they are initializing react-native. If that makes sense I can create a new PR to add that documentation.

While we figure that out, can we merge this PR?

**Comment by akshetpandey** [comment]
@thymikee : Sorry for bothering you, but is there anything I can do to get this merged. This blocks v1 release of https://github.com/akshetpandey/react-native-cronet for me.

**Comment by thymikee** [comment]
@akshetpandey yep, a brief mention in the docs please :D See https://github.com/react-native-community/cli/pull/653#issuecomment-526100009 if you missed it

**Comment by akshetpandey** [comment]
I added some documentation in [docs/autolinking.md](https://github.com/react-native-community/cli/blob/master/docs/autolinking.md#platform-android) as that seems to be a more appropriate place than docs/dependencies.md

**Comment by thymikee** [comment]
Thank you!

**Pull request merged**
