### PR TITLE
fix: use execa to spawn jetifier

### PR DESCRIPTION
**Pull request by thymikee**
Summary:
---------

Hopefully this resolves Windows issues. cc @theweavrs 	

Fixes https://github.com/facebook/react-native/issues/25667

Test Plan:
----------

Works on Windows

### CODE REVIEW

**Comment by theweavrs** [comment]
@thymikee checking now

**Comment by Inovassist-dev** [comment]
Anxious for a resolution!

**Comment by theweavrs** [comment]
@thymikee confirmed. Works like a charm!

**Comment by theweavrs** [comment]
@thymikee confirmed. Works like a charm!

**Comment by jsieler** [comment]
When it will be live?

**Comment by thymikee** [comment]
It's already published in cli v2.6.2

**Pull request merged**
