### PR TITLE
feat(yarn): prefer local react-native insteda of global one using npx

### PR DESCRIPTION
**Pull request by sibelius**
Summary:
---------

run local react-native cli version, so it does not have some kind of mismatch of react-native version

Test Plan:
----------

Run against a monorepo using yarn workspaces without nohoist option

### CODE REVIEW

**Comment by sibelius** [comment]
before this fix the error was like this one

```jsx
A problem occurred evaluating script.
> React Native CLI failed to determine Android project configuration. This is likely due to misconfiguration. Config output:
  [root:/app/packages/app/android, reactNativePath:/app/node_modules/react-native, dependencies:[:], commands:[], assets:[], platforms:[:], haste:[providesModuleNodeModules:[], platforms:[]], project:[:]]
```

**Comment by sibelius** [comment]
can we use `npm start react-native config` ?

**Comment by thymikee** [comment]
No, we can't. "start" usually (and likely not always, as projects differ) runs metro and won't work with extra "config" argument. Can you share a repro where the problem happens so we can investigate?

**Comment by sibelius** [comment]
like this https://github.com/entria/entria-fullstack

but we need to remove nohoist on that

**Comment by sibelius** [comment]
worked well here https://github.com/entria/entria-fullstack with npx

gonna need more time to figure it out why our internal repo is failing

I'm gonna reopen if I figure it out

**Pull request closed without merging**
