### PR TITLE
chore: replace azure with github actions

### PR DESCRIPTION
**Pull request by dulmandakh**
Summary:
---------

Replace Azure Pipelines with GitHub Actions for efficient testing on multiple platforms.

Test Plan:
----------

GitHub Actions will produce same results and errors as Azure Pipelines

### CODE REVIEW

**Comment by dulmandakh** [comment]
@thymikee could you please review and merge 👍

**Comment by thymikee** [comment]
Ideas why it doesn't show up in checks?

**Comment by dulmandakh** [comment]
Because it's not merged yet. You can got into my fork and check actions in it.

**Review by thymikee — APPROVED** [review]
Thanks!

**Pull request merged**
