### PR TITLE
chore: upgrade Jest to 26

### PR DESCRIPTION
**Pull request by thymikee**
Summary:
---------

New release is up https://jestjs.io/blog/2020/05/05/jest-26. 
With this upgrade I've changed the runner to `jest-circus`, which will be the default in next Jest major, and hopefully fixed flaky config tests (started to by consistent on my machine). Apparently `rimraf` doesn't remove all directories in the tree at times, which resulted in leaks from previous test cases.

Test Plan:
----------

Green CI

### CODE REVIEW

**Comment by thymikee** [comment]
We need to drop Node 8 to land this, so moving to v5.x major

**Comment by grabbou** [comment]
On hold, let's resume working on `5.x` now and plan to ship something within this month.

**Comment by grabbou** [comment]
We're at Node 10 now, so this can go.

**Comment by thymikee** [comment]
Rebased

**Comment by grabbou** [comment]
Appreciate!

**Pull request merged**
