### PR TITLE
Add Windows info to react-native info

### PR DESCRIPTION
**Pull request by asklar**
Summary:
---------

This PR adds information about Windows-specific SDK and IDE necessary for react-native-windows, to `react-native info`.
It builds on a recent change I made to `envinfo` to expose this information.

Test Plan:
----------

Manually ran: `node .\packages\cli\build\bin.js info` on Windows. Relying on CI to validate other platforms.

image

### CODE REVIEW

**Comment by asklar** [comment]
@Esemesek @grabbou @thymikee looks like some test failed in CI but I see it pass locally, could you re-run the github actions test and kindly review this PR :) ?

**Comment by asklar** [comment]
FYI I need another change that will be in 7.8.0 so marked this as draft until it's ready, thanks for reviewing :)

**Comment by asklar** [comment]
@grabbou @Esemesek could you guys take a look?

**Comment by asklar** [comment]
I don't have a mac to test this on (only Windows) so I'd love to get someone to try this on a mac before we merge it.
The changes in 7.7.2 have a bug in mac that will crash when asking for the installed browsers.
However, the react-native CLI explicitly does not ask for browsers (see cli/build/tools/envinfo.js)

```js
  const info = await _envinfo().default.run({
    System: ['OS', 'CPU', 'Memory', 'Shell'],
    Binaries: ['Node', 'Yarn', 'npm', 'Watchman'],
    IDEs: ['Xcode', 'Android Studio'],
    Managers: ['CocoaPods'],
    Languages: ['Java', 'Python'],
    SDKs: ['iOS SDK', 'Android SDK'],
    npmPackages: ['react', 'react-native', '@react-native-community/cli'],
    npmGlobalPackages: ['*react-native*']
  }, options);
```

So I think this means we will not hit the mac crash but I'd love someone to help me verify this on a mac
The fix for the mac crash is https://github.com/tabrindle/envinfo/pull/185
CC @alloy

**Comment by alloy** [comment]
(I’m OOO, so unsure when I’ll be able to test this. If somebody else has a minute before me, testing this would be much appreciated 🙏 /cc @acoates-ms )

**Comment by acoates-ms** [comment]
I ran through the info command on a mac.  Seems to run just fine.

**Comment by alloy** [comment]
Great, thanks! :shipit:

**Pull request merged**
