### PR TITLE
fix link dependencies use monorepo

### PR DESCRIPTION
**Pull request by yozman**
Summary:
---------

fix <https://github.com/react-native-community/cli/issues/537>

Test Plan:
----------

### CODE REVIEW

**Comment by thymikee** [comment]
@maciejsimka is onto fixing that, maybe let's wait for him

**Comment by yozman** [comment]
@thymikee 
> Node_modules may not always be there, e.g. when working with local native modules.

I think it should be a npm package folder with package.json in this case.

> @maciejsimka is onto fixing that, maybe let's wait for him

ok

**Comment by maciejsimka** [comment]
[Here's](https://github.com/react-native-community/cli/pull/550) what I came up with. @yozman would you mind verifying if this works in your case?

**Comment by yozman** [comment]
@maciejsimka 
nice job, works for me

**Pull request closed without merging**
