### PR TITLE
Fixed cannot start Android emulator version 34.1.20.0

### PR DESCRIPTION
**Pull request by doothez**
Fixes https://github.com/react-native-community/cli/issues/2350

```
» npm run android 

> connectedCoffee@0.0.1 android
> react-native run-android

info Launching emulator...
error Failed to launch emulator. Reason: The emulator (INFO    | Storing crashdata in: /tmp/android-sung.lee/emu-crash-34.1.20.db, detection is enabled for process: 30977) quit before it finished opening. You can try starting the emulator manually from the terminal with: /Users/sung.lee/Library/Android/sdk/emulator/emulator @INFO    | Storing crashdata in: /tmp/android-sung.lee/emu-crash-34.1.20.db, detection is enabled for process: 30977.
warn Please launch an emulator manually or connect a device. Otherwise app may fail to launch.
```

```

» emulator
INFO    | Storing crashdata in: /tmp/android-sung.lee/emu-crash-34.1.20.db, detection is enabled for process: 37429
INFO    | Android emulator version 34.1.20.0 (build_id 11610631) (CL:N/A)
ERROR   | No AVD specified. Use '@foo' or '-avd foo' to launch a virtual device named 'foo'

» emulator -list-avds
INFO    | Storing crashdata in: /tmp/android-sung.lee/emu-crash-34.1.20.db, detection is enabled for process: 37459
Pixel_7a_API_33

```

Test Plan:
----------

```
 » npm run android 

> connectedCoffee@0.0.1 android
> react-native run-android

info A dev server is already running for this project on port 8081.
info Launching emulator...
info Successfully launched emulator.
info Installing the app...

> Configure project :expo

Using expo modules
  - expo-application (5.8.3)
  - expo-av (13.10.5)
  - expo-constants (15.4.5)
  - expo-file-system (16.0.8)
  - expo-font (11.10.3)
  - expo-haptics (12.8.1)
  - expo-keep-awake (12.8.2)
  - expo-modules-core (1.11.12)
  - expo-modules-core$android-annotation (1.11.12)
  - expo-modules-core$android-annotation-processor (1.11.12)


> Task :app:installDebug
Installing APK 'app-debug.apk' on 'emulator-5554 - 13' for :app:debug
Installed on 1 device.

Deprecated Gradle features were used in this build, making it incompatible with Gradle 9.0.

You can use '--warning-mode all' to show the individual deprecation warnings and determine if they come from your own scripts or plugins.

For more on this, please refer to https://docs.gradle.org/8.3/userguide/command_line_interface.html#sec:command_line_warnings in the Gradle documentation.

BUILD SUCCESSFUL in 19s
496 actionable tasks: 26 executed, 470 up-to-date
info Connecting to the development server...
8081
info Starting the app on "emulator-5554"...
Starting: Intent { act=android.intent.action.MAIN cat=[android.intent.category.LAUNCHER] cmp=com.connectedcoffee/.MainActivity }
```

Checklist
----------

- [*] Documentation is up to date to reflect these changes.
- [*] Follows commit message convention described in [CONTRIBUTING.md](https://github.com/react-native-community/cli/blob/main/CONTRIBUTING.md#commit-message-convention)

### CODE REVIEW

**Review by szymonrybczak — APPROVED** [review]
Thanks! 👍 Could you please fix linter issues?

**Comment by whtjs** [comment]
I think checking `INFO    | ` can make same issue when emulator return other kind of message like `ERROR    | ` or `WARNING    | `. And it will not work when emulator change white space number. How about change code to check each line does not include whitespace? I test by adding whitespace to AVD's name in OS X and WINDOWS but they trim it when print it. So i think AVD name will never  have whitespace whereas other messages have.

**Comment by szymonrybczak** [comment]
> How about change code to check each line does not include whitespace? 

I agree, @doothez do you mind updating Pull Request with feedback from @whtjs?

**Comment by whtjs** [comment]
I think this must be shipped at next update. Do you have some opinion about it? @doothez  If your too busy to change it. Can i fix it if you don't mind?

**Comment by doothez** [comment]
> I think this must be shipped at next update. Do you have some opinion about it? @doothez If your too busy to change it. Can i fix it if you don't mind?

Sorry for the late response, I was traveling, please feel free to update it, I'm OK~!

**Pull request closed without merging**
