### PR TITLE
chore: fix tests on Windows

### PR DESCRIPTION
**Pull request by thymikee**
Summary:
---------

An attempt to fix the tests on Windows.

Test Plan:
----------

Green CI

### CODE REVIEW

**Comment by thymikee** [comment]
@Esemesek feel free to jump on the last 2 failing tests:
- one is about `glob` returning forward slashes even on windows (so either convert path separators in source code or adjust this test to additionally replace forward slashes on windows)
- second one kinda worries me, because it seems like the files are not copied recursively, however Windows users didn't report anything like it, so it's probably something in our testing setup

**Comment by thymikee** [comment]
@theweavrs it would be lovely if you could help me finish this PR up! <3

**Comment by theweavrs** [comment]
@thymikee sure, how can I help?

**Comment by thymikee** [comment]
By fixing the tests that are still failing and sending a PR to this branch (`fix/windows`) 😄

**Comment by thymikee** [comment]
Thank you @theweavrs ❤️

**Pull request merged**
