### PR TITLE
fix: add cocoapods requirement

### PR DESCRIPTION
**Pull request by Gray-Wind**
As file is using `Pod`, cocoapods should be imported.

Summary:
---------

This PR might solve this issue: https://github.com/CocoaPods/Core/issues/601

### CODE REVIEW

**Comment by thymikee** [comment]
@alloy @orta can you advise here?

**Comment by orta** [comment]
I think this should be fine, normally when running for `pod install` CocoaPods has to have been included at some point. If you're calling this code another way, then it's possible to not be set up.

To get the CI green, I think it will need a `gem install cocoapods` before running the tests

**Comment by Gray-Wind** [comment]
I'm not sure where to do it. In CircleCI config? Just add another step to install this dependency?

**Comment by orta** [comment]
Hrm, these other failing tests look pretty worrying - unsure what's going on there though. I don't feel like they should be affected by these changes

**Comment by Gray-Wind** [comment]
I noticed, that tests are failing for a long time already: https://github.com/react-native-community/cli/commits/master

**Comment by alloy** [comment]
The require wasn’t there previously to keep the test suite light-weight. However, it’s probably better to not mock and actually require the env 👍

**Comment by Gray-Wind** [comment]
I've dropped mocking cocoapods, as there is no more need.

But test is failing because of

```
--- expected
+++ actual
@@ -1 +1 @@
-["Detected React Native module pod for ios-dep", "Detected React Native module pods for ios-dep, and ios-dep"]
+["Detected React Native module pod for ios-dep", "Detected React Native module pods for ios-dep and ios-dep"]
```

This error shouldn't be related to changes in this branch.

**Comment by Gray-Wind** [comment]
Should I do something else?

**Comment by alloy** [comment]
Yeah update that test, it’s probably using the real ActiveSupport `to_sentence` implementation now.

**Comment by Gray-Wind** [comment]
Done.

**Comment by alloy** [comment]
Nice, thanks! This looks good to me 👍 the one thing is those failing CI tests…

It’s true that those have been failing previously as well, but for the last commit the results were:

```
Test Suites: 1 failed, 67 passed, 68 total
Tests:       5 failed, 2 skipped, 2 todo, 252 passed, 261 total
Snapshots:   6 failed, 19 passed, 25 total
```

Whereas for this PR the results are:

```
Test Suites: 2 failed, 66 passed, 68 total
Tests:       6 failed, 2 skipped, 2 todo, 251 passed, 261 total
Snapshots:   6 failed, 19 passed, 25 total
```

So it looks like there may have been additional regression?

**Comment by Gray-Wind** [comment]
I think it is flakiness of tests themselves. You could check not the last, but previous one and there are 2 failed tests:
https://github.com/react-native-community/cli/runs/305041507

**Comment by alloy** [comment]
Gotcha, works for me 👍 

@thymikee What’s the process of this repo? Should I squash & merge and add `fix` to the commit message to cut a patch release?

**Comment by thymikee** [comment]
We don't have an automated release yet, but I'll edit the message and merge myself then :)

**Pull request merged**
