### PR TITLE
feat: upgrade Android Studio version when installing on Windows

### PR DESCRIPTION
**Pull request by szymonrybczak**
Summary:
---------

https://github.com/react-native-community/cli/issues/2068

Test Plan:
----------
1. Clone the repository and do all the required steps from the [Contributing guide](https://github.com/react-native-community/cli/blob/main/CONTRIBUTING.md)
2. Run this command:

```sh
node /path/to/react-native-cli/packages/cli/build/bin.js doctor
```

3. Check if Android Studio is installing correctly on Windows when using automatic fix.

Checklist
----------

- [x] Documentation is up to date to reflect these changes.
- [x] Follows commit message convention described in [CONTRIBUTING.md](https://github.com/react-native-community/cli/blob/main/CONTRIBUTING.md#commit-message-convention)

### CODE REVIEW

**Comment by thymikee** [comment]
Mind providing some screenshot to back up it works on Windows? I don't have my machine set up

**Comment by Ashackq** [comment]
> @Ashackq mind testing this? 🙏 If you need some help I can help you 🙌
Sure 
I've forked the branch and cloned it
what next?

**Comment by szymonrybczak** [comment]
@Ashackq just follow steps described [here](https://github.com/react-native-community/cli/blob/main/CONTRIBUTING.md).

**Comment by Ashackq** [comment]
> @Ashackq just follow steps described [here](https://github.com/react-native-community/cli/blob/main/CONTRIBUTING.md).

ok everything's set up
how do I test the changes?

**Comment by szymonrybczak** [comment]
@Ashackq just checkout this branch I use [Github CLI](https://github.com/cli/cli) for that, and rebuild all packages with `yarn` and just run `yarn doctor` and try to run automatic fix.

**Comment by Ashackq** [comment]
> @Ashackq just checkout this branch I use [Github CLI](https://github.com/cli/cli) for that, and rebuild all packages with `yarn` and just run `yarn doctor` and try to run automatic fix.

hey @szymonrybczak 
the new android studio version is getting downloaded and working perfectly fine and all the issue are getting fixed with the doctor.🥳

**Pull request merged**
