### PR TITLE
chore: replace inquirer with prompts

### PR DESCRIPTION
**Pull request by thymikee**
Summary:
---------

`prompts` is lighter and faster alternative to `inquirer`. The biggest advantage of this change is dropping `rxjs`, which accounts for >4.8MB in node_modules

Test Plan:
----------

CI, please test manually as well.

### CODE REVIEW

**Comment by thymikee** [comment]
Thanks @lucasbento! Should be good now

**Comment by lucasbento** [comment]
Cool, now you can select the options.

But you still get inconsistency in the UI:

<details>
<summary>Before</summary>

image
</details>

<details>
<summary>After</summary>

image
</details>

`CocoaPods` and the URL with `enquirer` are also not in bold.

**Comment by thymikee** [comment]
Gave it a moment, but enquirer behaves inconsistently with questions that take more than 1 line in terminal. If someone is interested in helping me out, please do

**Comment by doowb** [comment]
Hi, I'm a maintainer on `enquirer` and I just noticed this PR. If you have any questions, I'm happy to try to answer them.

**Comment by thymikee** [comment]
Awesome, thanks for chiming in @doowb! The issue I have is that when having a prompt which spans multiple lines and also have multiple choices, the cursor, after selecting an option, returns to a different position, depending on chosen answer. It seems to be related to the question being long and multiline. I don't have a minimal repro though, haven't got time to put it up yet.

**Comment by doowb** [comment]
> I don't have a minimal repro though, haven't got time to put it up yet.

If you are able to put together a minimal repo, let me know and I'll take a closer look. I experimented a little today, but I'm not exactly sure how to reproduce the issue you mention.

**Comment by thymikee** [comment]
@doowb here's an issue description with a repro you can download, hope that helps : https://github.com/enquirer/enquirer/issues/268

**Comment by brodybits** [comment]
> enquirer/enquirer#268

It looks to me like they fixed the issue back in March and then published a couple new patches. It would definitely benefit the `create-react-native-module` & `react-native-module-init` utilities that I am maintaining.

**Comment by thymikee** [comment]
@brodybits could you verify this? The maintainer mentioned waiting for major release and looking at published commits I can't see a reference to anything similar to the issue we have. Help appreciated :)

**Comment by brodybits** [comment]
My bad, I have to say that I found the conversation in <https://github.com/enquirer/enquirer/issues/268> to be a little bit confusing. I just followed up in that conversation.

**Review by beatrizf13 — APPROVED** [review]

**Comment by grabbou** [comment]
It would be great to ship this one. Do changes here potentially affect the work that @acoates-ms done in the other PR? 

CC: @thymikee

**Comment by thymikee** [comment]
We're still blocked by enquirer/enquirer#268. No rush tho, this is just a "nice to have".

**Comment by thymikee** [comment]
As an alternative we may also try using [prompts](https://www.npmjs.com/package/prompts)

**Comment by thymikee** [comment]
Inspired by this tweet https://twitter.com/Baconbrix/status/1330852677325119493 I've gave `prompts` a try and it seems to works nicely in our case. Allowing us to drop bloated `rxjs` as well :)

cc @lucasbento to test this once again 😅

**Comment by grabbou** [comment]
I am good with that change. I will hold to @brunolemos report and we're good to go.

**Comment by NickGerleman** [comment]
I'm not sure if this is still relevant, but I rmemebr testing prompts vs inquirer earlier this year for a tool in react-native-windows and found that prompts had some surprising behavior for at least number prompts. The free-form number prompt would reset itself if you typed slowly and there were some oddities around pasting free-form text as well, at least on Windows. I could have been on a bad build though. 

The typings for prompts are *much* higher quality than the ones for inquirer though. The answers object gets typed with question name and type based on prompt type. I've actually introduced two separate bugs from missing type safety on the inquirer answers object 😂.

**Comment by thymikee** [comment]
@NickGerleman thanks for your insights! Will try to keep that in mind. Our usecase is solely "choose from a fixed set of options" and it seems to work just fine :)

**Comment by brunolemos** [comment]
>  I will hold to @brunolemos report and we're good to go.

I think you meant @lucasbento 

> The biggest advantage of this change is dropping rxjs, which accounts for >4.8MB in node_modules

I noticed `rxjs` is still getting installed because `lerna` has the `inquirer` dependency:

```
$ yarn why rxjs

=> Found "rxjs@6.5.4"
   - "_project_#lerna#@lerna#clean#@lerna#prompt#inquirer" depends on it
   - Hoisted from "_project_#lerna#@lerna#clean#@lerna#prompt#inquirer#rxjs"
info Disk size without dependencies: "16.92MB"
info Disk size with unique dependencies: "16.99MB"
info Disk size with transitive dependencies: "16.99MB"
```

Maybe move `lerna` to `devDependencies` but `rxjs` may still get installed anyway.

**Comment by thymikee** [comment]
@brunolemos Lerna is a dev dependency already (it's in the workspace root). The difference is that now our users won't have rxjs pulled into their node_moduled, so it's a big win.

**Comment by brunolemos** [comment]
> it's in the workspace root

oh, true. cool!

**Comment by grabbou** [comment]
I have tested manually and looks like all visual regressions as reported by @lucasbento are gone.

Screenshot 2020-12-07 at 13 35 00
Screenshot 2020-12-07 at 13 36 14

Shipping it. We can always do some follow-ups, but overall, it looks good!

**Pull request merged**
